CREATE TABLE billing.servicerequest (
	registrationno varchar(100) NULL,
	patientidentifierno varchar(50) NULL,
	requestid numeric NOT NULL,
	requesteddeptid varchar(50) NULL,
	requestdate timestamp NULL,
	createdby varchar(50) NULL,
	updatedby varchar(50) NULL,
	updateddate timestamp NULL,
	locationid varchar(50) NOT NULL,
	companyid varchar(20) NULL,
	patientserviceid numeric NULL,
	biliingtype numeric NULL,
	customerid numeric NULL,
	bedcategoryid numeric NULL,
	billingservice varchar(10) NULL,
	requestno varchar(100) NULL,
	patienttypeid numeric NULL,
	createddate timestamp NULL,
	doctorid varchar(30) NULL,
	requeststatus varchar(50) DEFAULT NULL::character varying NULL,
	admissionnoteno varchar(50) NULL,
	status numeric DEFAULT 1 NULL,
	agreementid numeric NULL,
	requestedfromurl varchar(100) NULL,
	remarks varchar(350) NULL,
	transferlocationid varchar(50) NULL,
	baselocationid varchar(50) NULL,
	CONSTRAINT servicerequest_pk PRIMARY KEY (requestid, locationid)
);
