CREATE TABLE billing.servicerequestdetails (
	servicerequestdetailsid numeric NOT NULL,
	requestid numeric NOT NULL,
	serviceid numeric NULL,
	billingstatus varchar(20) NULL,
	servicestatus varchar(100) NULL,
	bedcategoryid numeric NULL,
	createdby varchar(100) NULL,
	updatedby varchar(100) NULL,
	updateddate timestamp NULL,
	createddate timestamp NULL,
	servicename varchar(200) NULL,
	servicetypeid numeric NULL,
	locationid varchar(50) NULL,
	mappedpackageid numeric NULL,
	requestno varchar(100) NULL,
	includedinpackage varchar(2) NULL,
	fnbservicerequestid numeric NULL,
	bloodbagno varchar(50) NULL,
	bloodtype varchar(50) NULL,
	startdatetime timestamp NULL,
	enddatetime timestamp NULL,
	payerid numeric NULL,
	authrequestid numeric NULL,
	authrequestedflag numeric NULL DEFAULT 0,
	doctorid varchar(20) NULL,
	doctorfeetypeid numeric NULL,
	consultationdate timestamp NULL,
	consultationtime varchar(50) NULL,
	authstatusid numeric NULL,
	requestedbedcategoryid numeric NULL,
	allotedbedcategoryid numeric NULL,
	billablebedcategoryid numeric NULL,
	pkgroomrent numeric NULL,
	pkgicu numeric NULL,
	servicedetailindex numeric NULL,
	requestdate timestamp NULL,
	doctorfeeamount numeric NULL,
	upgradedpackageid numeric NULL,
	requestedquantity numeric NULL DEFAULT 1,
	billno varchar(50) NULL,
	extrachargeflag varchar(5) NULL,
	billabledate timestamp NULL,
	applicabledate timestamp NULL,
	packageexcluded varchar(20) NULL,
	creditnoteissued bpchar(1) NULL DEFAULT 'N'::bpchar,
	creditnotetranid numeric NULL,
	remarks varchar(350) NULL,
	degradedpackageid numeric NULL,
	promodiscount bpchar(1) NULL,
	patientpayable bpchar(1) NULL,
	bedsideflag varchar(5) NULL,
	issecondary bpchar(1) NULL
)PARTITION BY RANGE (SERVICEREQUESTDETAILSID);