CREATE TABLE billing.generalaccountmaster (
	cumdebitamount numeric(20, 4) DEFAULT 0 NULL,
	cumcreditamount numeric(20, 4) DEFAULT 0 NULL,
	accountstatus varchar(100) NULL,
	accountcreationdate timestamp NULL,
	accountclosedate timestamp NULL,
	locationid varchar(100) NOT NULL,
	amountblockedip numeric(20, 4) DEFAULT 0 NULL,
	amountblockedop numeric(20, 4) DEFAULT 0 NULL,
	currencycode varchar(10) NULL,
	customerid varchar(100) NULL,
	companyid varchar(100) NULL,
	createdby varchar(50) NULL,
	createddate timestamp NULL,
	accountno varchar(100) NOT NULL,
	waiverallowed varchar(100) NULL,
	updateddate timestamp NULL,
	updatedby varchar(100) NULL,
	accounttype bpchar(1) NULL,
	cumminimumdeposit numeric DEFAULT 0 NULL,
	packagedueamount numeric NULL,
	remarks varchar(350) NULL,
	CONSTRAINT pk_generalaccountmaster PRIMARY KEY (accountno)
);