FROM python:3.12-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt-get update && apt-get install -y build-essential python3-dev && rm -rf /var/lib/apt/lists/*


WORKDIR /app
COPY . /app


RUN pip install -r requirements.txt

CMD ["streamlit", "run", "streamlit_app.py"]