ddl_statements = [
    """CREATE TABLE registration.registrationmaster (
	registrationid numeric(19) NOT NULL,
	registrationtype numeric(10) NOT NULL,
	registrationsource varchar(100) NULL,
	registrationdescription varchar(100) NULL,
	updateddate timestamp NOT NULL,
	updatedby varchar(100) NOT NULL,
	CONSTRAINT pk_registrationmaster PRIMARY KEY (registrationid)
);""",
"""CREATE TABLE registration.patient (
	registrationid numeric(19) NOT NULL,
	preregistrationno varchar(50) NULL,
	emergencyno varchar(100) NULL,
	uhid varchar(100) NULL,
	locationid numeric(10) NULL,
	corporateemployeeid varchar(100) NULL,
	corporateid numeric(19) NULL,
	refferaldoctorid numeric(19) NULL,
	refferalentityid numeric(19) NULL,
	employeeid varchar(100) NULL,
	recruitmentid varchar(100) NULL,
	employeereferralid numeric(10) NULL,
	relationshipcode numeric(10) NULL,
	campid varchar(100) NULL,
	campname varchar(100) NULL,
	camptype varchar(100) NULL,
	campregistrationid varchar(100) NULL,
	batchid varchar(100) NULL,
	title varchar(200) NULL,
	firstname varchar(200) NULL,
	middlename varchar(200) NULL,
	lastname varchar(200) NULL,
	sufix varchar(200) NULL,
	educationalqualification varchar(200) NULL,
	otherdegree varchar(200) NULL,
	birthdate timestamp NULL,
	birthtime timestamp NULL,
	fathername varchar(200) NULL,
	spousename varchar(200) NULL,
	mothermaidenname varchar(200) NULL,
	gaurdianname varchar(200) NULL,
	birthplace varchar(200) NULL,
	approximate numeric(10) NULL,
	age numeric(10) NULL,
	agetype numeric(10) NULL,
	agecategory numeric(10) NULL,
	gender varchar(200) NULL,
	maritalstatus varchar(200) NULL,
	religion varchar(200) NULL,
	race varchar(200) NULL,
	ethnicgroup varchar(200) NULL,
	employmentstatus varchar(200) NULL,
	monthlyincome numeric(19, 4) NULL,
	primarylanguage varchar(200) NULL,
	translatorrequired varchar(200) NULL,
	translatorname varchar(200) NULL,
	citizenship varchar(200) NULL,
	literate varchar(200) NULL,
	financialstatus varchar(200) NULL,
	emotionalbarriers varchar(200) NULL,
	patienttype varchar(200) NULL,
	disability varchar(200) NULL,
	disabledpersoncode bpchar(20) NULL,
	disabledpersonidentifier varchar(100) NULL,
	identificationmark1 varchar(200) NULL,
	identificationmark2 varchar(200) NULL,
	socialsecuritynumber varchar(100) NULL,
	possesspassport varchar(200) NULL,
	diabetic numeric(10) NULL,
	allergic numeric(10) NULL,
	bloodgroup bpchar(20) NULL,
	rhfactor varchar(40) NULL,
	donor numeric(10) NULL,
	donortype bpchar(20) NULL,
	organtype bpchar(20) NULL,
	donorcode bpchar(20) NULL,
	paymentforregistration numeric(10) NULL,
	paymentcurrency varchar(100) NULL,
	paymentmethod varchar(100) NULL,
	referenceno varchar(200) NULL,
	createdby varchar(50) NULL,
	createddate timestamp NULL,
	howdoyoucometoknowaboutus varchar(200) NULL,
	preferredmodeofcontact varchar(200) NULL,
	wantalertsonhospitalpromotions numeric(10) NULL,
	filetype varchar(100) NULL,
	status numeric(10) NOT NULL,
	business varchar(100) NULL,
	preferredlocation bpchar(40) NULL,
	privacystatus bpchar(20) NULL,
	customerstatus varchar(100) NULL,
	aliasname varchar(100) NULL,
	startdate timestamp NULL,
	enddate timestamp NULL,
	noofissues numeric(10) NULL,
	updatedby varchar(100) NULL,
	updateddate timestamp NULL,
	flexifield1 varchar(100) NULL,
	flexifield2 varchar(100) NULL,
	flexifield3 varchar(100) NULL,
	flexifield4 varchar(100) NULL,
	filename varchar(200) NULL,
	filepath varchar(2000) NULL,
	emailid varchar(200) NULL,
	cancellationdate timestamp NULL,
	reasonforcancellation varchar(400) NULL,
	babyof varchar(200) NULL,
	reasonforreissue varchar(400) NULL,
	counterno varchar(100) NULL,
	shiftno varchar(100) NULL,
	draft numeric NULL,
	tempdraftid varchar(100) NULL,
	ismlccase numeric NULL,
	mlccaseno varchar(800) NULL,
	ishypertension numeric NULL,
	havecommunicabledisease numeric NULL,
	patientpreference varchar(4000) NULL,
	foodpreference varchar(4000) NULL,
	diabetictype varchar(400) NULL,
	deathdatetime timestamp NULL,
	employeerelation varchar(200) NULL,
	eventid varchar(200) NULL,
	eventname varchar(200) NULL,
	eventtype varchar(200) NULL,
	currentstatus numeric(2) DEFAULT 0 NULL,
	lasttransaction timestamp NULL,
	reasonforfree varchar(4000) NULL,
	olduhid varchar(200) NULL,
	referralpatientuhid varchar(100) NULL,
	mothersuhid varchar(100) NULL,
	customerloyaltyno varchar(100) NULL,
	flag numeric NULL,
	regularizationcheck numeric(38) NULL,
	regularizationdate timestamp NULL,
	secondarylanguage varchar(1000) NULL,
	bloodgroupflag numeric(1) DEFAULT 0 NULL,
	baselocation numeric(10) DEFAULT NULL::numeric NULL,
	transferdate timestamp NULL,
	releasedate timestamp NULL,
	emergencyflag numeric(1) DEFAULT 0 NULL,
	emrgncdate timestamp NULL,
	emrlocation numeric(10) NULL,
	edocid numeric(10) NULL,
	"source" varchar(10) NULL,
	CONSTRAINT pk_patient_regstrnid PRIMARY KEY (registrationid)
);""",
"""CREATE TABLE registration.addressmaster (
	registrationid numeric(19) NOT NULL,
	addresstypeid numeric(10) NOT NULL,
	street varchar(200) NULL,
	locality varchar(200) NULL,
	country numeric(19) NULL,
	state numeric(19) NULL,
	district numeric(19) NULL,
	city numeric(19) NULL,
	address1 varchar(500) NULL,
	address2 varchar(500) NULL,
	residencenumber varchar(100) NULL,
	officenumber varchar(100) NULL,
	"extension" varchar(100) NULL,
	mobilenumber varchar(100) NULL,
	emergencynumber varchar(100) NULL,
	residencefaxnumber varchar(100) NULL,
	officefaxnumber varchar(100) NULL,
	primaryemail varchar(200) NULL,
	alternateemail varchar(200) NULL,
	pincode varchar(40) NULL,
	contactnumber1 varchar(100) NULL,
	contactnumber2 varchar(100) NULL,
	startdate timestamp NULL,
	enddate timestamp NULL,
	status numeric(10) NULL,
	updatedby varchar(100) NULL,
	updateddate timestamp NULL,
	flexifield1 varchar(100) NULL,
	flexifield2 varchar(100) NULL
);

ALTER TABLE registration.addressmaster ADD CONSTRAINT fk_taddtype_taddress FOREIGN KEY (addresstypeid) REFERENCES registration.addresstypemaster(addresstypeid);""",
"""CREATE TABLE registration.patientvisadetail (
	registrationid numeric(19) NOT NULL,
	nationality varchar(200) NULL,
	internationalpatient varchar(200) NULL,
	countryissued numeric(10) NULL,
	passportnumber varchar(100) NULL,
	passportissuedate timestamp NULL,
	passportexpirydate timestamp NULL,
	visatype varchar(100) NULL,
	visaissuingauthority varchar(100) NULL,
	visaissuedate timestamp NULL,
	visaexpirydate timestamp NULL,
	startdate timestamp NULL,
	enddate timestamp NULL,
	status numeric(10) NULL,
	updatedby varchar(100) NULL,
	updateddate timestamp NULL,
	flexifield1 varchar(100) NULL,
	flexifield2 varchar(100) NULL,
	CONSTRAINT pk_patientvisadetail PRIMARY KEY (registrationid)
);""",
"""CREATE TABLE billing.patientpolicymaster (
	patientpolicymasterid numeric NOT NULL,
	locationid varchar(50) NULL,
	registrationno varchar(100) NOT NULL,
	billingtypeid numeric NULL,
	createdby varchar(100) NULL,
	createddte timestamp NULL,
	updatedby varchar(100) NULL,
	updateddate timestamp NULL,
	CONSTRAINT pk_policymaster PRIMARY KEY (patientpolicymasterid)
);""",
"""CREATE TABLE IF NOT EXISTS BILLING.OPMASTER

(OPMASTERID numeric,
LOCATIONID varchar(50),
REGISTRATIONNO varchar(100),
PATIENTIDENTIFIERNO varchar(100),
PATIENTNAME varchar(200),
BILLINGTYPEID numeric,
PATIENTSERVICEID numeric,
CREATEDBY varchar(100),
CREATEDDATE timestamp without time zone ,
UPDATEDBY varchar(100),
UPDATEDDATE timestamp without time zone ,
PATIENTTYPEID numeric,
PRIMARYDOCTORID numeric,
REFERRALDOCTORID numeric,
CUSOTMERID numeric,
AGREEMENTID numeric,
VISITNO numeric,
WARDSOPNUMBER varchar(100),
ISGENFROMREG bpchar(1),
DELETEFLAG numeric DEFAULT 1,
OTREQUESTNUMBER varchar(50),
SERVICEID numeric,
SERVICEAMOUNT numeric,
PRISM_FLAG numeric);
""",
"""CREATE TABLE billing.servicerequest (
	registrationno varchar(100) NULL,
	patientidentifierno varchar(50) NULL,
	requestid numeric NOT NULL,
	requesteddeptid varchar(50) NULL,
	requestdate timestamp NULL,
	createdby varchar(50) NULL,
	updatedby varchar(50) NULL,
	updateddate timestamp NULL,
	locationid varchar(50) NOT NULL,
	companyid varchar(20) NULL,
	patientserviceid numeric NULL,
	biliingtype numeric NULL,
	customerid numeric NULL,
	bedcategoryid numeric NULL,
	billingservice varchar(10) NULL,
	requestno varchar(100) NULL,
	patienttypeid numeric NULL,
	createddate timestamp NULL,
	doctorid varchar(30) NULL,
	requeststatus varchar(50) DEFAULT NULL::character varying NULL,
	admissionnoteno varchar(50) NULL,
	status numeric DEFAULT 1 NULL,
	agreementid numeric NULL,
	requestedfromurl varchar(100) NULL,
	remarks varchar(350) NULL,
	transferlocationid varchar(50) NULL,
	baselocationid varchar(50) NULL,
	CONSTRAINT servicerequest_pk PRIMARY KEY (requestid, locationid)
);
""",
"""CREATE TABLE billing.servicerequestdetails (
	servicerequestdetailsid numeric NOT NULL,
	requestid numeric NOT NULL,
	serviceid numeric NULL,
	billingstatus varchar(20) NULL,
	servicestatus varchar(100) NULL,
	bedcategoryid numeric NULL,
	createdby varchar(100) NULL,
	updatedby varchar(100) NULL,
	updateddate timestamp NULL,
	createddate timestamp NULL,
	servicename varchar(200) NULL,
	servicetypeid numeric NULL,
	locationid varchar(50) NULL,
	mappedpackageid numeric NULL,
	requestno varchar(100) NULL,
	includedinpackage varchar(2) NULL,
	fnbservicerequestid numeric NULL,
	bloodbagno varchar(50) NULL,
	bloodtype varchar(50) NULL,
	startdatetime timestamp NULL,
	enddatetime timestamp NULL,
	payerid numeric NULL,
	authrequestid numeric NULL,
	authrequestedflag numeric NULL DEFAULT 0,
	doctorid varchar(20) NULL,
	doctorfeetypeid numeric NULL,
	consultationdate timestamp NULL,
	consultationtime varchar(50) NULL,
	authstatusid numeric NULL,
	requestedbedcategoryid numeric NULL,
	allotedbedcategoryid numeric NULL,
	billablebedcategoryid numeric NULL,
	pkgroomrent numeric NULL,
	pkgicu numeric NULL,
	servicedetailindex numeric NULL,
	requestdate timestamp NULL,
	doctorfeeamount numeric NULL,
	upgradedpackageid numeric NULL,
	requestedquantity numeric NULL DEFAULT 1,
	billno varchar(50) NULL,
	extrachargeflag varchar(5) NULL,
	billabledate timestamp NULL,
	applicabledate timestamp NULL,
	packageexcluded varchar(20) NULL,
	creditnoteissued bpchar(1) NULL DEFAULT 'N'::bpchar,
	creditnotetranid numeric NULL,
	remarks varchar(350) NULL,
	degradedpackageid numeric NULL,
	promodiscount bpchar(1) NULL,
	patientpayable bpchar(1) NULL,
	bedsideflag varchar(5) NULL,
	issecondary bpchar(1) NULL
)PARTITION BY RANGE (SERVICEREQUESTDETAILSID);""",
"""CREATE TABLE billing.generalaccountmaster (
	cumdebitamount numeric(20, 4) DEFAULT 0 NULL,
	cumcreditamount numeric(20, 4) DEFAULT 0 NULL,
	accountstatus varchar(100) NULL,
	accountcreationdate timestamp NULL,
	accountclosedate timestamp NULL,
	locationid varchar(100) NOT NULL,
	amountblockedip numeric(20, 4) DEFAULT 0 NULL,
	amountblockedop numeric(20, 4) DEFAULT 0 NULL,
	currencycode varchar(10) NULL,
	customerid varchar(100) NULL,
	companyid varchar(100) NULL,
	createdby varchar(50) NULL,
	createddate timestamp NULL,
	accountno varchar(100) NOT NULL,
	waiverallowed varchar(100) NULL,
	updateddate timestamp NULL,
	updatedby varchar(100) NULL,
	accounttype bpchar(1) NULL,
	cumminimumdeposit numeric DEFAULT 0 NULL,
	packagedueamount numeric NULL,
	remarks varchar(350) NULL,
	CONSTRAINT pk_generalaccountmaster PRIMARY KEY (accountno)
);"""
]